# Generated by Django 5.2.7 on 2025-10-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        ("student", "0002_alter_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(related_name="courses", to="student.student"),
        ),
    ]
