# Generated by Django 5.2.7 on 2025-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_students"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_order_per_course"
            ),
        ),
    ]
