# Generated by Django 5.2.7 on 2025-10-26 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"profile": "INSTRUCTOR"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_instructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
