# Generated by Django 5.2.7 on 2025-10-26 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_access",
        ),
    ]
