# Generated by Django 5.2.7 on 2025-10-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_last_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.CharField(
                choices=[("ADMIN", "Administrator"), ("MEMBER", "Member")],
                max_length=12,
            ),
        ),
    ]
